
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: medi
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234medi
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/medi
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234medi
      SPRING_DATASOURCE_DRIVER: com.mysql.cj.jdbc.Driver
      API_TOKEN_SECRET: 1234fSecret
    networks:
      - backend-network

networks:
  backend-network:

volumes:
  mysql-data:
